version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/app

  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    env_file:
      - .env

  wait-for-db:
    image: wait-for-it
    depends_on:
      - db
    command: ["wait-for-it", "db:5432", "--timeout=30", "--", "sh", "-c", "python manage.py migrate"]